# Generated by Django 6.1.1 on 2026-09-05 05:21

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique employee code, e.g. EMP001', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank institution name', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', help_text='Account / IBAN number', max_length=50)),
                ('bank_ifsc_or_swift', models.CharField(blank=True, default='', help_text='Routing / IFSC / SWIFT code', max_length=50)),
                ('date_of_joining', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Payrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. September 2026 Regular Payrun', max_length=150)),
                ('start_date', models.DateField(help_text='Period start date (e.g. 2026-09-01)')),
                ('end_date', models.DateField(help_text='Period end date (e.g. 2026-09-30)')),
                ('payment_date', models.DateField(blank=True, help_text='Date disbursements are made', null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('validated', 'Validated'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payrun',
                'verbose_name_plural': 'Payruns',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic Salary, HRA, Provident Fund', max_length=150)),
                ('code', models.CharField(help_text='Variable name used in formulas, e.g. BASIC, HRA, PF, GROSS, NET', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Salary'), ('ALLOWANCE', 'Allowance'), ('GROSS', 'Gross'), ('DEDUCTION', 'Deduction'), ('NET', 'Net Salary')], max_length=20)),
                ('sequence', models.IntegerField(default=10, help_text='Execution sequence (smaller numbers computed first, e.g. BASIC=10, HRA=20, GROSS=50, PF=60, NET=100)')),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Another Rule'), ('formula', 'Python Formula Expression')], default='fixed', max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('percentage_base_code', models.CharField(blank=True, help_text="Code of rule to calculate percentage against, e.g. 'BASIC' or 'GROSS'", max_length=50, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage value, e.g. 40.00 for 40%', max_digits=6)),
                ('formula', models.TextField(blank=True, help_text='Python expression. Available variables: contract, employee, worked_days, rules (dict of computed rules). e.g.: contract.wage * 0.5', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Rule',
                'verbose_name_plural': 'Salary Rules',
                'ordering': ['sequence', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='Unique structure identifier, e.g. REG_FT', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard 40 Hours/Week', max_length=100, unique=True)),
                ('average_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Expected working hours per day', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Working Schedule',
                'verbose_name_plural': 'Working Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Alice Smith - Full Time Contract 2026', max_length=150)),
                ('wage', models.DecimalField(decimal_places=2, help_text='Monthly wage or base rate used in salary calculations', max_digits=12)),
                ('wage_type', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly')], default='monthly', max_length=20)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if permanent / open-ended', null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.employee')),
                ('salary_structure', models.ForeignKey(blank=True, help_text='Default salary structure assigned to this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.salarystructure')),
                ('working_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.workingschedule')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-start_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('worked_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('basic_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('validated', 'Validated'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core.employee')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.payrun')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core.salarystructure')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['payrun', 'employee__code'],
                'unique_together': {('payrun', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Rule code snapshot (e.g. BASIC, HRA, PF)', max_length=50)),
                ('name', models.CharField(help_text='Rule name snapshot', max_length=150)),
                ('category', models.CharField(help_text='BASIC, ALLOWANCE, GROSS, DEDUCTION, NET', max_length=20)),
                ('sequence', models.IntegerField(default=10)),
                ('rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage rate applied (e.g. 100%)', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Base calculation amount', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Final calculated line amount', max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.payslip')),
                ('salary_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_lines', to='core.salaryrule')),
            ],
            options={
                'verbose_name': 'Payslip Line',
                'verbose_name_plural': 'Payslip Lines',
                'ordering': ['payslip', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payrun',
            name='salary_structure',
            field=models.ForeignKey(help_text='Salary structure applied to this payrun batch', on_delete=django.db.models.deletion.PROTECT, related_name='payruns', to='core.salarystructure'),
        ),
        migrations.CreateModel(
            name='SalaryStructureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=10, help_text='Override or structure-specific evaluation sequence')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_rules', to='core.salaryrule')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_rules', to='core.salarystructure')),
            ],
            options={
                'verbose_name': 'Structure Rule Assignment',
                'verbose_name_plural': 'Structure Rule Assignments',
                'ordering': ['structure', 'sequence', 'rule__sequence'],
                'unique_together': {('structure', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('work_from', models.TimeField(default='09:00:00')),
                ('work_to', models.TimeField(default='17:00:00')),
                ('hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.workingschedule')),
            ],
            options={
                'verbose_name': 'Schedule Day',
                'verbose_name_plural': 'Schedule Days',
                'ordering': ['schedule', 'day_of_week', 'work_from'],
                'unique_together': {('schedule', 'day_of_week', 'work_from')},
            },
        ),
    ]
