# Generated by Django 6.1.1 on 2026-09-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_company_employee_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
