# Generated by Django 6.1.1 on 2026-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleday',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Break duration in hours', max_digits=4),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this schedule is currently active'),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='timezone',
            field=models.CharField(blank=True, default='Company Timezone', help_text='Timezone for this working schedule', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='work_to',
            field=models.TimeField(default='18:00:00'),
        ),
    ]
