# Generated by Django 6.1.1 on 2026-09-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_created_by_employee_updated_by'),
        ('core', '0004_scheduleday_break_hours_workingschedule_is_active_and_more'),
    ]

    operations = [
    ]
