# Generated by Django 6.1.1 on 2026-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260905_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingschedule',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', help_text='Timezone for this working schedule', max_length=100),
        ),
    ]
