# Generated by Django 6.1.1 on 2026-09-05 15:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_workingschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date of attendance')),
                ('check_in', models.DateTimeField(blank=True, help_text='Check-in timestamp', null=True)),
                ('check_out', models.DateTimeField(blank=True, help_text='Check-out timestamp', null=True)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total worked hours', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours worked beyond contract schedule', max_digits=5)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-check_in', 'employee'],
            },
        ),
    ]
