# Generated by Django 6.1.1 on 2026-09-05 23:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='notes',
            field=models.TextField(blank=True, help_text='Configuration or policy notes'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_allocation',
            field=models.BooleanField(default=True, help_text='Requires approved allocation balance before request'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='days', help_text='Unit of time off (Days or Hours)', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='e.g. 2026 Annual Allocation', max_length=200)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total days granted in this allocation', max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('refused', 'Refused')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=2026, help_text='Validity year for this allocation')),
                ('notes', models.TextField(blank=True, help_text='Notes or reason for allocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='core.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_allocations', to='core.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Allocation',
                'verbose_name_plural': 'Leave Allocations',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
